### ISSUE TITLE
When using relative blog_dir path: File Not Found when exporting images

### ISSUE THREAD

**Issue by commandlinegirl** [hemanta212/blogger-cli#16]
Hello,

Interesting tool! I'm trying it out to create a blog post from a Jupyter notebook. I'm getting a File Not Found error when exporting a notebook:

```
  1 $ blogger convert binary_img_classification_pipeline-pytorch.ipynb -b pytorch_image_classification
  2 
  3 CONVERTING 1 FILES
  4 :: Meta tags: <!-- --> Not found
  5 :: Got topic, 
  6 :: Found 8 images
  7 :: Detected DATA URI img. Writing to pytorch_image_classification/images/binary_img_classification_pipeline-pytorch/image_1.png
  8 :: Detected DATA URI img. Writing to pytorch_image_classification/images/binary_img_classification_pipeline-pytorch/image_2.png
  9 Traceback (most recent call last):
 10   File "/Users/ker/miniconda2/envs/sci/bin/blogger", line 11, in <module>
 11     sys.exit(cli())
 12   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/click/core.py", line 764, in __call__
 13     return self.main(*args, **kwargs)
 14   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/click/core.py", line 717, in main 
 15     rv = self.invoke(ctx)
 16   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
 17     return _process_result(sub_ctx.command.invoke(sub_ctx))
 18   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/click/core.py", line 956, in invoke
 19     return ctx.invoke(self.callback, **ctx.params)
 20   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/click/core.py", line 555, in invoke
 21     return callback(*args, **kwargs)
 22   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
 23     return ctx.invoke(f, obj, *args, **kwargs)
 24   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/click/core.py", line 555, in invoke
 25     return callback(*args, **kwargs)
 26   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/blogger_cli/commands/cmd_convert.py", line 81, in cli
 27     filenames_meta = convert_and_copyfiles(ctx)
 28   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/blogger_cli/commands/convert_utils/classifier.py", line 22, in convert_and_copyfiles
 29     html_filename_meta = converter(ctx, file)
 30   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/blogger_cli/converter/ipynb_to_html.py", line 22, in convert_and_copy_to_blog
 31     html_body, meta)
 32   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/blogger_cli/converter/ipynb_to_html.py", line 141, in write_html_and_ipynb
 33     ipynb_topic_filename)
 34   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/blogger_cli/converter/extractor.py", line 30, in extract_and_write_static
 35     extract_images(ctx, images, static_path, filename, blog_post_dir)
 36   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/blogger_cli/converter/extractor.py", line 110, in extract_images
 37     blog_post_dir)
 38   File "/Users/ker/miniconda2/envs/sci/lib/python3.6/site-packages/blogger_cli/converter/extractor.py", line 128, in extract_and_write_uri
 39     with open(static_path, 'wb') as wf:
 40 FileNotFoundError: [Errno 2] No such file or directory: 'pytorch_image_classification/images/binary_img_classification_pipeline-pytorch/image_2.png'
 41 (
```

The contents of the `images/` dir after executing the above command is:

```
$ ls -l pytorch_image_classification/images/binary_img_classification_pipeline-pytorch/
total 24
-rw-r--r--@ 1 azalcman  staff  9235 Aug  2 15:55 image_1.png
```

The notebook is: https://github.com/commandlinegirl/machine-learning/blob/master/histopathologic-cancer-detection/binary_img_classification_pipeline-pytorch.ipynb

Have I missed anything?

**Comment by hemanta212** [comment]
Please give me configurations of blog by:
```
blogger info <blogname>
```
Also ensure you have the version 1.0.2.
```
blogger info -V
```

**Comment by commandlinegirl** [comment]
Thanks for checking it out. The `info` output is:

```
$ blogger info pytorch_image_classification

Blogger-cli version: 1.0.2

Blog Name: pytorch_image_classification
Configurations:
   blog_dir -> pytorch_image_classification
   blog_images_dir -> images
   blog_posts_dir -> blog_posts
   disqus_username -> None
   google_analytics_id -> None
   templates_dir -> None
   working_dir -> .
```

My `tree` output is the following (the notebook `binary_img_classification_pipeline-pytorch.ipynb` is in the current working dir, at the same level as the blog dir):

```
$ tree
.
├── binary_img_classification_pipeline-pytorch.ipynb
└── pytorch_image_classification
    ├── _blogger_templates
    │   ├── css.html
    │   ├── dark_theme.html
    │   ├── disqus.html
    │   ├── google_analytics.html
    │   ├── js.html
    │   ├── layout.html
    │   ├── li_tag.html
    │   ├── light_theme.html
    │   ├── mathjax.html
    │   ├── navbar.html
    │   └── navbar_data.html
    ├── assets
    │   └── css
    │       ├── bootstrap.min.css
    │       ├── custom.css
    │       ├── dark_theme.css
    │       ├── font-awesome.min.css
    │       ├── light_theme.css
    │       └── python_syntax.css
    ├── blog
    │   └── index.html
    ├── blog_posts
    ├── images
    │   └── binary_img_classification_pipeline-pytorch
    │       └── image_1.png
    └── index.html
```

**Comment by hemanta212** [comment]
The blog dir should be absolute path upto the fokder like

C:\users\... or ~/.... or 
/home/user/... 

Also the working dir is not required for conversion, it's only use case is when you use 
```
blogger convert
```
without specifying the file or folder to convert. It is just a folder which blogger regularly checks for modified files to convert from so you don't have to cd into it and yes its value should be absolute as well.

As far as your notebook is concerned, I have tested it and it converts fine.

**Comment by hemanta212** [comment]
I just replicated your tree structure and configs and could reproduce your errors. However when the blog_dir is set to absolute path like F:\test\test_blog\ then the error resolves.

However, I guess i could also convert relative paths to absolute automatically after configs setup. 
For further conversion errors, you may want to use;
```
blogger convert -b <blogname> file/folder -o full/path/of/output/folder/
```
To distinguish if the error is in blog configs or in the conversion process.

I greatly appreciate the time you took for submitting this issue and following up.
